### ISSUE TITLE
Tries to download clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz, but I'm on Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by CGQAQ** [grailbio/bazel-toolchain#207] opened 2023-08-30 07:46 UTC
<details><summary>Details</summary>
<p>

```
INFO: Build option --incompatible_enable_cc_toolchain_resolution has changed, discarding analysis cache.
INFO: ToolchainResolution: Target platform //:linux_x64: Selected execution platform @local_config_platform//:host, 
INFO: ToolchainResolution: Target platform //:linux_x64: Selected execution platform @local_config_platform//:host, 
INFO: ToolchainResolution: Target platform @local_config_platform//:host: Selected execution platform @local_config_platform//:host, 
INFO: Repository llvm_toolchain_llvm instantiated at:
  /root/repos/WebKit/WORKSPACE:48:15: in <toplevel>
  /root/.cache/bazel/_bazel_root/19dc6c9a0347f6b82b4ee3ee2fc20006/external/com_grail_bazel_toolchain/toolchain/rules.bzl:289:13: in llvm_toolchain
Repository rule llvm defined at:
  /root/.cache/bazel/_bazel_root/19dc6c9a0347f6b82b4ee3ee2fc20006/external/com_grail_bazel_toolchain/toolchain/rules.bzl:266:23: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm_toolchain_llvm':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/19dc6c9a0347f6b82b4ee3ee2fc20006/external/com_grail_bazel_toolchain/toolchain/internal/repo.bzl", line 36, column 35, in llvm_repo_impl
                updated_attrs = _download_llvm(rctx)
        File "/root/.cache/bazel/_bazel_root/19dc6c9a0347f6b82b4ee3ee2fc20006/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 297, column 56, in download_llvm
                urls, sha256, strip_prefix = _distribution_urls(rctx)
        File "/root/.cache/bazel/_bazel_root/19dc6c9a0347f6b82b4ee3ee2fc20006/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 330, column 13, in _distribution_urls
                fail("Unknown LLVM release: %s\nPlease ensure file name is correct." % basename)
Error in fail: Unknown LLVM release: clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
Please ensure file name is correct.
ERROR: /root/repos/WebKit/WORKSPACE:48:15: fetching llvm rule //external:llvm_toolchain_llvm: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/19dc6c9a0347f6b82b4ee3ee2fc20006/external/com_grail_bazel_toolchain/toolchain/internal/repo.bzl", line 36, column 35, in llvm_repo_impl
                updated_attrs = _download_llvm(rctx)
        File "/root/.cache/bazel/_bazel_root/19dc6c9a0347f6b82b4ee3ee2fc20006/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 297, column 56, in download_llvm
                urls, sha256, strip_prefix = _distribution_urls(rctx)
        File "/root/.cache/bazel/_bazel_root/19dc6c9a0347f6b82b4ee3ee2fc20006/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 330, column 13, in _distribution_urls
                fail("Unknown LLVM release: %s\nPlease ensure file name is correct." % basename)
Error in fail: Unknown LLVM release: clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
Please ensure file name is correct.
ERROR: /root/.cache/bazel/_bazel_root/19dc6c9a0347f6b82b4ee3ee2fc20006/external/llvm_toolchain/BUILD.bazel:134:10: @llvm_toolchain//:all-components-x86_64-linux depends on @llvm_toolchain_llvm//:bin in repository @llvm_toolchain_llvm which failed to fetch. no such package '@llvm_toolchain_llvm//': Unknown LLVM release: clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
Please ensure file name is correct.
ERROR: Analysis of target '//:bun-webkit' failed; build aborted: 
INFO: Elapsed time: 12.678s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 7578 targets configured)
``` 

</p>
</details>

**Comment by sebastian-freitag** [comment] 2023-10-05 12:33
I have the same problem for 17. 
I added to my /etc/apt/sources.list:
```
deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main
deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main
```
And I set:
```
llvm_version = "17.0.0",
```

And I get the following problem:
```
ERROR: An error occurred during the fetch of repository 'llvm_toolchain_llvm':
   Traceback (most recent call last):
	File "/home/sfreitag/.cache/bazel/_bazel_sfreitag/cfc4cc6d3189db79e0bb2b51ac42a171/external/toolchains_llvm/toolchain/internal/repo.bzl", line 281, column 35, in llvm_repo_impl
		updated_attrs = _download_llvm(rctx)
	File "/home/sfreitag/.cache/bazel/_bazel_sfreitag/cfc4cc6d3189db79e0bb2b51ac42a171/external/toolchains_llvm/toolchain/internal/llvm_distributions.bzl", line 348, column 56, in download_llvm
		urls, sha256, strip_prefix = _distribution_urls(rctx)
	File "/home/sfreitag/.cache/bazel/_bazel_sfreitag/cfc4cc6d3189db79e0bb2b51ac42a171/external/toolchains_llvm/toolchain/internal/llvm_distributions.bzl", line 391, column 13, in _distribution_urls
		fail("Unknown LLVM release: %s\nPlease ensure file name is correct." % basename)
Error in fail: Unknown LLVM release: clang+llvm-17.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
Please ensure file name is correct.
```

**Comment by garymm** [comment] 2023-12-15 03:15
This is not a bug or FR @siddharthab I suggest you close it.

**Comment by siddharthab** [comment] 2023-12-15 04:38
Thanks!

**Closed** 2023-12-15 04:38 UTC
