### ISSUE TITLE
Link error when changing LLVM_VERSION to 13.0.1 for llmv_toolchain_with_sysroot

### ISSUE THREAD

**Issue by storypku** [grailbio/bazel-toolchain#164] opened 2022-11-30 15:22 UTC
Hi there,
    When I changed `LLVM_VERSION` of [tests/WORKSPACE](https://github.com/grailbio/bazel-toolchain/blob/master/tests/WORKSPACE#L28)
 from `14.0.0` to `13.0.1`, Running the following command on my Ubuntu 18.04 machine:

```
/usr/bin/bazel --bazelrc=/dev/null build --incompatible_enable_cc_toolchain_resolution --platforms=@com_grail_bazel_toolchain//platforms:linux-x86_64 --extra_toolchains=@llvm_toolchain_with_sysroot//:cc-toolchain-x86_64-linux --symlink_prefix=/ --color=yes   //:stdlib_test 
``` 

failed with the following error:

```
ERROR: /work/github/bazel-toolchain.git/tests/BUILD.bazel:27:8: Linking stdlib_test failed: (Exit 1): cc_wrapper.sh failed: error executing command external/llvm_toolchain_with_sysroot/bin/cc_wrapper.sh @bazel-out/k8-fastbuild/bin/stdlib_test-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
ld.lld: error: unable to find library -l:libc++.a
ld.lld: error: unable to find library -l:libc++abi.a
ld.lld: error: unable to find library -l:libunwind.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //:stdlib_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.269s, Critical Path: 0.16s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

However, it's OK when using other `@llvm_toolchain_X` variants (e.g., ` --extra_toolchains=@llvm_toolchain//:cc-toolchain-x86_64-linux`, ` --extra_toolchains=@llvm_toolchain_with_system_llvm//:cc-toolchain-x86_64-linux`).

Maybe a `-L{}/lib".format(toolchain_path_prefix)` line should be added before https://github.com/grailbio/bazel-toolchain/blob/master/toolchain/cc_toolchain_config.bzl#L181 and similar lines?

**Comment by siddharthab** [comment] 2022-12-02 12:56
Confirmed that 13.0.0 and 13.0.1 do not work because of the error you pasted above. Also checked that 14.0.0 works.

The `-L` flag that you are suggesting, I expect to be added by the frontend. it could be that they tried to go in a different direction for version 13, but then reverted that change in 14.

I won't have time to look into this further. So this issue will have to wait for someone to pick it up.

**Comment by siddharthab** [comment] 2023-01-17 10:41
Closing this issue for now, but please reopen if there is new information.

**Closed by siddharthab** 2023-01-17 10:41 UTC
Labels: help wanted
