### ISSUE TITLE
Experiencing issues building with bazel 6.0.0

### ISSUE THREAD

**Issue by codergs90** [grailbio/bazel-toolchain#175] opened 2023-01-15 23:34 UTC
I am using `grailbio/bazel-toolchain` under my project https://github.com/codergs90/twinspica/blob/master/WORKSPACE#L31. Building the repo with bazel 4.0.0 works fine, but moving to 6.0.0 is causing issue mentioned [here](https://github.com/bazelbuild/bazel/issues/8622) . I am trying to understand how to fix this as in my Bazel files I don't use platform constraint as such but maybe depend on them as I am using the tool chain from this repo. 

I am bit lost as I am unable to figure out how to proceed forward. Error is as below:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

 $ bazel test src/hello_world/cpp:all
Starting local Bazel server and connecting to it...
DEBUG: Rule 'com_grail_bazel_toolchain' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "17ce24a4c70f9397578a690e3b38d74a33cdcf78c34b4d2a0e70867dacf4f159"
DEBUG: Repository com_grail_bazel_toolchain instantiated at:
  /workspaces/twinspica/WORKSPACE:42:13: in <toplevel>
Repository rule http_archive defined at:
  /home/codespace/.cache/bazel/_bazel_codespace/1d6f179956fc48340ee6463a61a18cfb/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: /home/codespace/.cache/bazel/_bazel_codespace/1d6f179956fc48340ee6463a61a18cfb/external/bazel_tools/platforms/BUILD:84:6: in alias rule @bazel_tools//platforms:linux: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /home/codespace/.cache/bazel/_bazel_codespace/1d6f179956fc48340ee6463a61a18cfb/external/bazel_tools/platforms/BUILD:84:6: Analysis of target '@bazel_tools//platforms:linux' failed
ERROR: /workspaces/twinspica/src/hello_world/cpp/BUILD:53:9: While resolving toolchains for target //src/hello_world/cpp:hello_world_test: invalid registered toolchain '@go_sdk//:go_js_wasm': 
ERROR: Analysis of target '//src/hello_world/cpp:hello_world_test' failed; build aborted: 
INFO: Elapsed time: 93.182s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (36 packages loaded, 211 targets configured)
ERROR: Couldn't start the build. Unable to run tests
```
Any help is much appreciated. Thanks!

**Comment by siddharthab** [comment] 2023-01-17 10:35
From the logs, it does not look like the issue is this toolchain. But in any case, there have been some recent changes to the toolchain around this issue. Can you try again please?

**Comment by siddharthab** [comment] 2023-01-17 10:44
Closing this issue but please reopen if the problem is still there and you believe it is from this toolchain.

**Closed** 2023-01-17 10:44 UTC
