### ISSUE TITLE
C++ stdlib flag not propagated

### ISSUE THREAD

**Issue by radustoenescu** [grailbio/bazel-toolchain#81] opened 2021-05-12 08:52 UTC
I'm trying to build a large project that, among others, includes `libmemcached`.

The build fails and, for that project the build config is:

```
Configuration summary for libmemcached version 1.0.18

   * Installation prefix:       /home/vagrant/.cache/bazel/_bazel_vagrant/53811f16d0054678ea1281275219cd40/execroot/axle/bazel-out/k8-fastbuild/bin/external/libmemcached/libmemcached.build_tmpdir/libmemcached
   * System type:               unknown-linux-gnu
   * Host CPU:                  x86_64
   * C Compiler:                clang version 12.0.0 (https://github.com/llvm/llvm-project/ b978a93635b584db380274d7c8963c73989944a1)
   * C Flags:                   -U_FORTIFY_SOURCE -fstack-protector -fno-omit-frame-pointer -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -no-canonical-prefixes -Wno-builtin-macro-redefined -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" -fdebug-prefix-map=/home/vagrant/.cache/bazel/_bazel_vagrant/53811f16d0054678ea1281275219cd40/execroot/axle/external/llvm_toolchain/=external/llvm_toolchain/  -g -O2 -Wno-unknown-pragmas -Wno-pragmas -Wextra -Wno-attributes -Waddress -Wvarargs -Warray-bounds -Wbad-function-cast -Wchar-subscripts -Wcomment -Wfloat-equal -Wformat-security -Wformat=2 -Wformat-y2k -Wmissing-field-initializers -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Woverride-init -Wpointer-arith -Wpointer-sign -Wredundant-decls -Wshadow -Wshorten-64-to-32 -Wsign-compare -Wstrict-overflow=1 -Wstrict-prototypes -Wswitch-enum -Wundef -Wunused -Wunused-result -Wunused-variable -Wunused-parameter -Wunused-local-typedefs -Wwrite-strings -fwrapv -pipe -fPIE -Wsizeof-pointer-memaccess -Wpacked
   * C++ Compiler:              clang version 12.0.0 (https://github.com/llvm/llvm-project/ b978a93635b584db380274d7c8963c73989944a1)
   * C++ Flags:                 -Wno-register -g -O2 -Wno-unknown-pragmas -Wno-pragmas -Wall -Wextra -Wno-attributes -Wvarargs -Waddress -Warray-bounds -Wchar-subscripts -Wcomment -Wctor-dtor-privacy -Wfloat-equal -Wformat=2 -Wformat-y2k -Wmissing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wredundant-decls -Wshadow -Wshorten-64-to-32 -Wsign-compare -Wstrict-overflow=1 -Wswitch-enum -Wundef -Wc++11-compat -Wunused -Wunused-result -Wunused-variable -Wunused-parameter -Wunused-local-typedefs -Wwrite-strings -Wformat-security -fwrapv -pipe -fPIE -Wsizeof-pointer-memaccess -Wpacked
   * CPP Flags:                  -fvisibility=hidden
   * LIB Flags:                 
   * Assertions enabled:        no
   * Debug enabled:             no
   * Shared:                    no
   * Warnings as failure:       no
   * SASL support:              no
   * make -j:                   9
   * VCS checkout:              no
```

The problem, I suspect is that `clang` uses `libstdc++` includes, whereas `lld` tries to link statically agains `libc++.a`.

What puzzles me is why
```
actions = all_cpp_compile_actions,
flag_groups = [flag_group(flags = ["-std=c++17", "-stdlib=libc++"])],
```
do not make it in the C++ flags used to compile `libmemcached`.

As a workaround, I tried forcing them into the flag set by adding the following to my `.bazelrc`:
```
build --cxxopt=-std=c++17
build --cxxopt=-stdlib=libc++
```

As I did a bit of digging I realized the problem might arise from `libmemcached` being built using [foreign cc rules](https://github.com/bazelbuild/rules_foreign_cc/blob/main/docs/README.md) that, for some reason, do not carry the `flag_groups = [flag_group(flags = ["-std=c++17", "-stdlib=libc++"])]` set of flags.

The naive approach to make sure those flags are used is to specifically add them for every project built using _foreign rules_, but that is quite tedious for a large scale project with many such dependencies.

**Is there a way to instruct Bazel to carry those flags to the dependencies built using _foreign cc rules_?**

**Comment by siddharthab** [comment] 2021-09-21 03:49
Can you please try again with the master branch.

We recently made some changes, and I added a test case for rules_foreign_cc (uses CMake). In the build script for my test (bazel-bin/tests/foreign/pcre_foreign_cc/build_script.sh), I do see the flags [-std=c++17, -stdlib=libc++]. So maybe this is already solved.

If CMake is working as intended, but `make` has a problem, then maybe something should change in rules_foreign_cc.

If you are still seeing the same behavior as before, then maybe attaching the build script for your dependency could help us investigate.

**Comment by siddharthab** [comment] 2021-09-23 20:16
I am going to close this issue, but please feel free to reopen if the problem persists.

**Closed by siddharthab** 2021-09-23 20:16 UTC
Labels: question
