### ISSUE TITLE
Automatic switching to sandboxed execution

### ISSUE THREAD

**Issue by igrekun** [grailbio/bazel-toolchain#131] opened 2022-01-04 12:27 UTC
When I pass chromium filegroup as sysroot like this
```
llvm_toolchain(
    name = "llvm_toolchain",
    llvm_version = "13.0.0",
    sysroot = {
        "linux-x86_64": "@org_chromium_sysroot_linux_x64//:sysroot",
    },
)
```

Bazel switches to sandboxed execution and initial build takes much longer. Is this correct and what's the reason behind this behaviour?
When I supply path to folder containing the sysroot it doesn't switch to sandbox.

**Comment by siddharthab** [comment] 2022-03-08 08:07
Yes, this is intended behavior. The use of sysroot as a bazel filegroup will slow down your builds considerably because the files are sandboxed for every step. This is to ensure hermeticity of the build. If I do not sandbox them, then bazel will not rerun your actions if any file in your sysroot change.

You may choose to completely forego hermeticity if you don't need it, and use absolute paths everywhere. See https://github.com/grailbio/bazel-toolchain#sandbox for this and more options to speed up your build.

I am going to close this issue now, but please feel free to reopen if the original issue is not addressed.

**Closed by siddharthab** 2022-03-08 08:07 UTC
